name: Frontend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build frontend container
      run: docker compose build frontend
    
    - name: Run frontend tests in container
      run: |
        docker compose run --rm frontend npm ci
        docker compose run --rm frontend npm run lint
        docker compose run --rm frontend npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/dist